name: build-docker-img

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docker-img:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with: 
          java-version: '8'
          distribution: 'adopt'
      - name: Build with maven
        run: mvn package
      - name: Build docket image
        run: docker build .
